name: Code Format Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Python formatters
      run: |
        python -m pip install --upgrade pip
        pip install black
        
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format
        
    - name: Check clang-format version
      run: clang-format --version
      
    - name: Check Black version
      run: black --version
      
    - name: Run Black check on Python files
      run: |
          echo "Checking Python files with Black..."
          black --check --diff .
        
    - name: Run clang-format check on C/C++ files
      run: |
          echo "Checking C/C++ files with clang-format..."
          find . -name "*.c" -o -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" -o -name "*.h" -o -name "*.hpp" | \
          xargs clang-format --dry-run --Werror